JERI_virtuelles_Energiesystemlabor/jeriapps/bilanzkreisspiel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from bilanzkreisspiel.views import *

from . import views

urlpatterns = [
    url(r'^$', views.gamestart, name='gamestart'),
]

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    url(r'^$', views.login, name='start'),
    url(r'^login', views.login, name='login'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^handler', views.handler, name='handler'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^admin', views.admin, name='admin'),
    url(r'^prefs', views.prefs, name='prefs'),
    url(r'^markets', views.externalmarkets, name='markets'),
    url(r'^hs', views.highscores, name='hs'),
    url(r'^rs', views.auctionsresults,name='results')
    
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.register, name='register'),
    url(r'^start_lobby$', views.start_lobby, name='start_lobby'),
    url(r'^lobby$', views.lobby, name='lobby'),
    url(r'^login_view$', views.login_view, name='login_view'),
    url(r'^logout_view$', views.logout_view, name='logout_view'),
    url(r'^all_lobbys$', views.all_lobbys, name='all_lobbys'),    
    
]

JERI_virtuelles_Energiesystemlabor/jeriapps/jeriapps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^boersenspiel/', include('boersenspiel.urls', namespace='boersenspiel')),
    url(r'^bilanzkreisspiel/', include('bilanzkreisspiel.urls', namespace='bilanzkreisspiel')),
    url(r'^gamemaster/', include('gamemaster.urls')),
]

urlpatterns += staticfiles_urlpatterns()

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from bilanzkreisspiel.models import *
from django.template.defaultfilters import default

class Lobby(models.Model):
    lobby_id = models.AutoField(primary_key=True)
    lobby_name = models.TextField()
    lobby_password = models.TextField()
    lobby_modus = models.TextField()
    
    def __unicode__(self):
        return self.lobby_name
   
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lobby = models.ForeignKey(Lobby, default='0', on_delete=models.CASCADE)
    
    # --- BilanzKreisSpieler Daten ---
    capital = models.IntegerField(default = 0)
    powerplantfleet = models.ForeignKey(PowerPlantFleet, default='0', on_delete=models.CASCADE)
    bks_status = models.BooleanField(default=False)
    bks_timeblock = models.ForeignKey(Timeblock, default='0', on_delete=models.CASCADE)
    #---Timeblock.objects.get(timeblock_number = -9999)
    
    # --- BörsenSpielSpieler Daten ---
    #---------------------------------
    def __unicode__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/forms.py
from django import forms

class RegForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password_req = forms.CharField(label='password wiederholen', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(RegForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Nickname'
        self.fields['password'].widget.attrs['placeholder'] = 'Passwort'
        self.fields['password_req'].widget.attrs['placeholder'] = 'Passwort wiederholen'
        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password_req'].widget.attrs['class'] = 'form-control'
        
        self.fields['username'].widget.attrs['name'] = 'reg_username'
        self.fields['password'].widget.attrs['name'] = 'reg_password'
        self.fields['password_req'].widget.attrs['name'] = 'reg_password_req'
        
class LoginForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Nickname'
        self.fields['password'].widget.attrs['placeholder'] = 'Passwort'
        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        
        
        self.fields['username'].widget.attrs['name'] = 'login_username'
        self.fields['password'].widget.attrs['name'] = 'login_password'
        
                

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from django.template.context_processors import request
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from gamemaster.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import *

# Create your views here.

def register(request):
    if request.method == 'POST':
        form_reg = RegForm(request.POST)
        form_login = LoginForm(request.POST)
        if form_reg.is_valid():
            
            username = form_reg.cleaned_data.get('username')
            password = form_reg.cleaned_data.get('password')
            password_req = form_reg.cleaned_data.get('password_req')
            
            if password == password_req:
                user = User.objects.create_user(username,'',password)
                user.save()
                
                g = Group.objects.get(name='Student') 
                g.user_set.add(user)
                form_login = LoginForm()
                return login_view(request)
            else:
                wrong = 'Passwörter stimmen nicht überein'
                return render(request, 'gamemaster/index.html', {'form_reg': form_reg, 'wrong': wrong}) 
            
    else:
        form_reg = RegForm()
        return render(request, 'gamemaster/index.html', {'form_reg': form_reg})
    
def start_lobby(request):
    wrongteacherpassword = ''
    if request.POST.get('submit'):
        
        tName = request.POST.get('TeacherName')
        tPassword = request.POST.get('TeacherPassword')
        user = authenticate(username = tName,password = tPassword)
        
        if user is not None:
            login(request, user)
            
            lobby = Lobby()
            lobby.lobby_name = request.POST.get('name')
            lobby.lobby_password =request.POST.get('PasswordLobby')
            lobby.lobby_modus = request.POST.get('gamemode')
            lobby.save()
            
        else:
            wrongteacherpassword = 'wrong teacher-password/name!'
            return render(request, 'gamemaster/teacher_login.html',{'wrong': wrongteacherpassword,})
        
    return render(request, 'gamemaster/teacher_login.html') #bearbeiten wenn Lobbyviews fertig sind!!!

def lobby(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            data = Lobby.objects.get(lobby_name=request.POST.get("lobbyname"))
            Profile.objects.filter(user=request.user).update(lobby=data)
            lobby_user = Profile.objects.filter(lobby=data)
            return render(request, 'gamemaster/lobby.html', {'data': data, 'lobby_user': lobby_user})
        else:
            data=Profile.objects.get(user=request.user).lobby
            lobby_user = Profile.objects.filter(lobby=data)
            return render(request, 'gamemaster/lobby.html', {'data': data, 'lobby_user': lobby_user})
    else:
        form_login = LoginForm(request.POST)
        if form_login.is_valid():
            
            username = form_login.cleaned_data.get('username')
            password = form_login.cleaned_data.get('password')
            
            user = authenticate(request,username=username,password=password)
            
            if user is not None:
                login(request, user)
                data=Lobby.objects.all()
                return render(request, 'gamemaster/all_lobbys.html', {'data': data})    
            else:
                wrong = 'Nickname oder Passwort falsch!'
                return render(request, 'gamemaster/login.html', {'form_login': form_login, 'wrong': wrong}) 
            
        
 
def all_lobbys(request):
    if request.user.is_authenticated():
        data=Lobby.objects.all()
        return render(request, 'gamemaster/all_lobbys.html', {'data': data})
    else:
        form_login = LoginForm(request.POST)
        if form_login.is_valid():
            
            username = form_login.cleaned_data.get('username')
            password = form_login.cleaned_data.get('password')
            
            user = authenticate(request,username=username,password=password)
            
            if user is not None:
                login(request, user)
                data=Lobby.objects.all()
                us = Profile.objects.all()
                return render(request, 'gamemaster/all_lobbys.html', {'data': data, 'us': us })    
            else:
                wrong = 'Nickname oder Passwort falsch!'
                return render(request, 'gamemaster/login.html', {'form_login': form_login, 'wrong': wrong}) 
            
        
        
    
def login_view(request):        
    form_login = LoginForm()
    return render(request, 'gamemaster/login.html', {'form_login': form_login})
        
def logout_view(request):
    form_login = LoginForm(request.POST)
    Profile.objects.filter(user=request.user).update(lobby='0')
    logout(request)
    wrong = 'Sie wurden erfolgreich ausgeloggt'
    return render(request, 'gamemaster/login.html', {'form_login': form_login, 'wrong': wrong}) 

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/all_lobbys.html
{% extends "gamemaster/base.html" %}

{% load bootstrap3 %}

{% block content %}

    <div class="wrapper">
        <!--
        {% if request.user.groups.all.0.name == 'Teacher' %}
            <div class="list_box rounded">Sie sind als 'Teacher' angemeldet</div>
        {% endif %}
        -->
        
        <div class="list_box rounded">Angemeldet als {{ request.user.groups.all.0 }}</div>
        <br /><br />
        <h1>Lobbyübersicht</h1>
        <br />
        <div class="list_box rounded">{{test}}
        {% for lobby in data %}   
        {% if lobby.lobby_id > 0 %}   
        
            {% if request.user.groups.all.0.name == 'Teacher' %}   
            
                <form action="{% url 'lobby' %}" method="post" name="join_lobby">  
                {% csrf_token %}         
                    <div class="row lobby_box rounded">
                        <div class="col-md-4"><input type="text" name="lobbyname" value="{{lobby.lobby_name}}"></div>
                        <div class="col-md-4">User: {{ lobby.profile_set.count }}</div>
                        <div class="col-md-3"><button class="btn btn-sm btn-primary float-right"  name="submit" value="Join Lobby" type="Submit">Join Lobby</button></div>
                        <div class="col-md-1">{% bootstrap_icon "trash" %} delete</div>
                    </div>
                </form>
                
            {% else %}
            
                <form action="{% url 'lobby' %}" method="post" name="join_lobby">  
                {% csrf_token %}         
                    <div class="row lobby_box rounded">
                        <div class="col-md-9"><input type="text" name="lobbyname" value="{{lobby.lobby_name}}"></div>
                        <div class="col-md-1">User: {{ lobby.profile_set.count }}</div>
                        <div class="col-md-2"><button class="btn btn-sm btn-primary float-right"  name="submit" value="Join Lobby" type="Submit">Join Lobby</button></div>
                    </div>
                </form>
            
            {% endif %}

        {% endif %}
        {% endfor %}
        </div>
        
    </div>

{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'gamemaster/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'gamemaster/css/custom_css.css' %}" rel="stylesheet">
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
        {% block nav %}
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Spiele</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'all_lobbys' %}">Lobbys</a>
      </li>
      {% endif%}
      {% if request.user.groups.all.0.name == 'Teacher' %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'start_lobby' %}">Start Lobby</a>
      </li>
      {% endif %}
    </ul>
    <div class="form-inline my-2 my-lg-0">
    
      <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout_view' %}"><span class="glyphicon glyphicon-user"></span>Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login_view' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Registration</a>
      </li>
      {% endif %}

    </ul>
    </div>
  </div>
</nav>
        {% endblock %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/index.html
{% extends "gamemaster/base.html" %}

{% block content %}

        <div class="wrapper">
            <form method="post" class="form-signin rounded">
            {% csrf_token %}
            {{form2.as_p}}
                <h3 class="form-signin-heading">Registrierung</h3>
    
                {% for field in form_reg %}
                    {{ field }}
        
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <button type="submit" class="btn btn-lg btn-primary btn-block">Registrieren</button>
                <font color="red">{{ wrong }}</font>
            </form>
       </div>

{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/lobby.html
{% extends "gamemaster/base.html" %}

{% block content %}

    <div class="wrapper">
        <!--
        {% if request.user.groups.all.0.name == 'Teacher' %}
            <div class="list_box rounded">Sie sind als 'Teacher' angemeldet</div>
        {% endif %}
        -->
        
        <div class="list_box rounded">Angemeldet als {{ request.user.groups.all.0 }}</div>
        <br /><br />
        <h1>Lobby {{data.lobby_name}}</h1>
        <br />
        <h3>Spielmodus: {% if data.lobby_modus == 'bks' %}Bilanzkreisspiel{% elif data.lobby_modus == 'bs' %}Börsenspiel{% else %}Kein Modus verfügbar{% endif %}</h3>
        <h3>Eingeloggte User: </h3>
        {% for user in lobby_user %}   
            <div class="row lobby_box rounded">
                <div class="col-md-6">{{ user.user.username }}</div> 
            </div>
        {% endfor %}
        <br />
            {% if data.lobby_modus == 'bks' %}<form action="{% url 'bilanzkreisspiel:gamestart' %}" method="post" name="join_lobby"> {% elif data.lobby_modus == 'bs' %}<form action="{% url 'boersenspiel:handler' %}" method="post" name="join_lobby">{% else %}Kein Modus verfügbar{% endif %}
             
            {% csrf_token %}     
                <button class="btn btn-sm btn-primary "  name="submit" value="Start Game" type="Submit">Zum Spiel</button>
            </form>   
        
        
    </div>

{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/login.html
{% extends "gamemaster/base.html" %}

{% block content %}

        <div class="wrapper">
        
            <form action="{% url 'all_lobbys' %}" method="post" class="form-signin rounded">
                {% csrf_token %}
                <h3 class="form-signin-heading">Login</h3>
                <font color="red">{{ wrong }}</font>
                {{form1.as_p}}
                {% for field in form_login %}
                    {{ field }}
        
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <button type="submit" class="btn btn-lg btn-primary btn-block">Login</button>
            </form> 
       </div>

{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/room.html
{% extends "gamemaster/base.html" %}

{% block content %}
  {% load staticfiles %}
  <h1>{{ room.label }}</h1>
  <p class="quiet">
    Anyone with this URL can join the room and chat: 
    <code>{{ request.scheme }}://{{ request.get_host }}/{{ room.label }}</code> 
  </p>
  <p>
    <label for="handle">Your name:</label>
    <input id="handle" type="text" placeholder="handle">
  </p>
  <form id="chatform">
    <table id="chat">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.handle }}</td>
            <td>{{ message.message }}</td>
          </tr> 
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>Say something:</td>
        <td colspan=2>
          <input id="message" type="text" placeholder="message">
          <button type="submit" id="go">Say it</button>
        </td>
      </tfoot>
    </table>
  </form>
{% endblock content %}

{% block afterbody %}
  <script type="text/javascript" src='{% static "jquery-1.12.1.min.js" %}'></script>
  <script type="text/javascript" src='{% static "reconnecting-websocket.min.js" %}'></script>
  <script type="text/javascript" src='{% static "chat.js" %}'></script>
{% endblock afterbody %}

JERI_virtuelles_Energiesystemlabor/jeriapps/gamemaster/templates/gamemaster/teacher_login.html
{% extends "gamemaster/base.html" %}

{% block content %}

        <div class="wrapper">
        <form action="start_lobby" method="post" name="Spielleiter_Freischaltung_Form" class="form-signin rounded">       
            <h3 class="form-signin-heading">Willkommen zur Spielleiterfreischaltung.</h3>
             {% csrf_token %}
                {{ form.as_p }}
                <input type="text" class="form-control" name="name" placeholder="Lobby Name" required=""/>
                <input type="password" class="form-control" name="PasswordLobby" placeholder="Lobby - Password" required=""/>
                
                    <p>Wählen sie einen Spielmodus</p> 
                    <fieldset>
                        <input type="radio" id="bks" name="gamemode" value="bks"><label for="bks">&nbsp;&nbsp;Bilanzkreisspiel</label><br> 
                        <input type="radio" id="bs" name="gamemode" value="bs"><label for="bs">&nbsp;&nbsp;Börsenspiel</label><br> 
                        <input type="radio" id="ae" name="gamemode" value="ms"><label for="ae">&nbsp;&nbsp;Michaelsspiel</label> 
                    </fieldset><br />
                <font color="red">{{ wrong }}</font>
                <input type="text" class="form-control" name="TeacherName" placeholder="Teacher - Name" required=""/>
                <input type="password" class="form-control" name="TeacherPassword" placeholder="Teacher - Password" required=""/>                 
                 
              <button class="btn btn-lg btn-primary btn-block"  name="submit" value="Login" type="Submit">Lobby erstellen</button>  
    
        </form>         
    </div>

{% endblock %}