JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    url(r'^$', views.login, name='start'),
    url(r'^login', views.login, name='login'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^handler', views.handler, name='handler'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^admin', views.admin, name='admin'),
    url(r'^prefs', views.prefs, name='prefs'),
    url(r'^markets', views.externalmarkets, name='markets'),
    url(r'^hs', views.highscores, name='hs'),
    url(r'^rs', views.auctionsresults,name='results')
    
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JERI_virtuelles_Energiesystemlabor/jeriapps/jeriapps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^boersenspiel/', include('boersenspiel.urls', namespace='boersenspiel')),
    url(r'^bilanzkreisspiel/', include('bilanzkreisspiel.urls', namespace='bilanzkreisspiel')),
    url(r'^gamemaster/', include('gamemaster.urls')),
]

urlpatterns += staticfiles_urlpatterns()

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime


# Create your models here.
class einstellungen(models.Model):
    Runde=models.IntegerField(default=0)
    idSpiel=models.IntegerField(default=1)
    auctiontype=models.IntegerField(default=1)
    nextround=models.DateTimeField(default=datetime.now, blank=True)
    rundenzeit=models.IntegerField(default=180)
    class Meta:
        verbose_name='Einstellungen'
        verbose_name_plural='Einstellungen'
            
class co2preise(models.Model):
    Runde=models.IntegerField(default=0)
    Preis=models.FloatField(default=0)
    class Meta:
        verbose_name='CO2 Preis'
        verbose_name_plural='CO2 Preise'
  
        
class brennstoffpreise(models.Model):
    idBrennstoff=models.IntegerField(default=0)
    Runde=models.IntegerField(default=0)
    Preis=models.FloatField(default=0)
    class Meta:
        verbose_name='Brennstoffpreis'
        verbose_name_plural='Brennstoffpeise'

class brennstoff(models.Model):
    id=models.IntegerField(default=0,primary_key=True)
    Name=models.CharField(max_length=30)
    EMF=models.FloatField(default=0)
    readonly_fields=('id',)
    class Meta:
        verbose_name='Brennstoff'
        verbose_name_plural='Brennstoffe'

class ergebnisse(models.Model):
    idSpiel=models.IntegerField(default=0)
    idSpieler=models.IntegerField(default=0)
    idRunde=models.IntegerField(default=0)
    erloes=models.IntegerField(default=0)
    kostenCo2=models.FloatField(default=0)
    kosten=models.FloatField(default=0)
    time=models.TimeField(default=datetime.now, blank=True)
    class Meta:
        verbose_name='Ergebnis'
        verbose_name_plural='Ergebnisse'
    
class boersenpreise(models.Model):
    runde=models.IntegerField(default=0)
    time=models.TimeField(default=datetime.now, blank=True)
    menge=models.IntegerField(default=0)
    preis=models.IntegerField(default=0)
    class Meta:
        verbose_name='Boersenpreis'
        verbose_name_plural='Boersenpreise'    
    
class lastgang(models.Model):
    idRunde=models.IntegerField(default=0)
    fMaxLast=models.FloatField(default=0)
    class Meta:
        verbose_name='Lastgang'
        verbose_name_plural='Lastgaenge'
        
class gebote(models.Model):
    idSpiel=models.IntegerField(default=0,null=True)
    idSpieler=models.IntegerField(default=0,null=True)
    Runde=models.IntegerField(default=0,null=True)
    idKW=models.IntegerField(default=0,null=True)
    idGebot=models.IntegerField(default=0,null=True)
    Time=models.TimeField(default=datetime.now, blank=True)
    Menge=models.IntegerField(default=0,null=True)
    Preis=models.IntegerField(default=0,null=True)
    class Meta:
        verbose_name='Gebot'
        verbose_name_plural='Gebote'
    
class kraftwerke(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=30)
    maxLeistung=models.IntegerField(default=0)
    verfuegbarkeit=models.FloatField(default=0)
    volllaststunden=models.IntegerField(default=0)
    idBrennstoff=models.IntegerField(default=0)
    wirkungsgrad=models.FloatField(default=0)
    fixkosten=models.FloatField(default=0)
    icon=models.CharField(max_length=50, blank=True, null=True)
    class Meta:
        verbose_name='Kraftwerke'
        verbose_name_plural='Kraftwerke'
    
class spielerkraftwerke(models.Model):
    """Kraftwerke des jeweiligen Spielers"""
    id=models.IntegerField(primary_key=True)
    idSpiel=models.IntegerField(default=0)
    idSpieler=models.IntegerField(default=0,null=True)
    idKraftwerk=models.IntegerField(default=0)   
    verkaufteEnergiemenge=models.IntegerField(default=0)
    gewinn=models.FloatField(default=0)
    class Meta:
        verbose_name='SpielderKraftwerk'
        verbose_name_plural='SpielerKraftwerke'

class Spieler(models.Model):
    """
    DB der Spieler, bindet das Standart User-Model von Django ein um die Authentifizierung, Login und  Sessions von Django zu benutzen
    Weitere Felder: 
    Boersenspiel: isAdmin, idSpiel, Deckungsbeitrag
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    idSpieler=models.AutoField(primary_key=True)
    isAdmin=models.BooleanField(default=False)
    idSpiel=models.IntegerField(default=1)
    deckungsbeitrag=models.IntegerField(default=0)
    readonly_fields=('id',)
    class Meta:
        verbose_name='Spieler'
        verbose_name_plural='Spieler'    
    

@receiver(post_save, sender=User)
def create_user_spieler(sender, instance, created, **kwargs):
    """Erstellung eines Users, erstellt auch das entsprechende Spieler Object """
    if created:
        spieler= Spieler.objects.create(user=instance)
        spieler.save()
        for kw in range(1,4):
            spielerkraftwerke.objects.create(idSpiel=spieler.idSpiel, idSpieler=spieler.idSpieler,idKraftwerk=kw)
            for bid in range (1,5):
                gebote.objects.create(idSpiel=spieler.idSpiel,idSpieler=spieler.idSpieler,Runde=einstellungen.objects.get().Runde,idKW=kw,idGebot=bid)
        

@receiver(post_save, sender=User)
def save_user_spieler(sender, instance, **kwargs):
    """Updates des User-Models updatet auch das Spieler Object"""
    instance.spieler.save()
    
      

    

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/forms.py
from django import forms

class bidscoal(forms.Form):
    kw11=forms.FloatField(label='Nr.1')
    kw12=forms.FloatField(label='Nr.2')
    kw13=forms.FloatField(label='Nr.3')
    kw14=forms.FloatField(label='Nr.4')

class bidsgas(forms.Form):
    kw21=forms.FloatField(label='Nr.1')
    kw22=forms.FloatField(label='Nr.2')
    kw23=forms.FloatField(label='Nr.3')
    kw24=forms.FloatField(label='Nr.4')
    
class bidswater(forms.Form):
    kw31=forms.FloatField(label='Nr.1')
    kw32=forms.FloatField(label='Nr.2')
    kw33=forms.FloatField(label='Nr.3')
    kw34=forms.FloatField(label='Nr.4')
    
class einstellungenForm(forms.Form):
    Runde=forms.IntegerField(label='Spielrunde')
    Spiel=forms.IntegerField(label='ID des Spiels')
    AT_CHOICES=((1,'Pay-as-bid'),(2,'Uniform'))
    auctiontype=forms.ChoiceField(choices=AT_CHOICES, label='Auktionstype')
    nextround=forms.DateTimeField(label='Start der naechsten Runde')
    rundenzeit=forms.IntegerField(label='Laenge der Runden in Sekunden')

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/views.py
from django.shortcuts import render,redirect
from django.http.response import Http404
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout 
from boersenspiel import fhandler as fh, fboersenspiel as fb, fadmin,\
    fboersenspiel
from django.contrib.auth.forms import UserCreationForm
from boersenspiel.forms import bidscoal,bidswater,bidsgas,  einstellungenForm
from boersenspiel.models import gebote,einstellungen, Spieler, spielerkraftwerke, kraftwerke
from boersenspiel.fboersenspiel import gib_Runde

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return handler(request)
    else:
        form = UserCreationForm()
    return render(request, 'boersenspiel/signup.html', {'form': form, 'runde':fboersenspiel.gib_Runde()})

def handler(request):
    
    if  not request.user.is_authenticated():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return handler(request)
            else:
                return redirect('login')
    else:
        formcoal=bidscoal(request.POST)
        formgas=bidsgas(request.POST)
        formwater=bidswater(request.POST)
        if formcoal.is_valid():
            for bid in range(1,5):
                gebotequery, created=gebote.objects.get_or_create(idSpieler=fb.gib_Spieler(request),idKW=1,idGebot=bid,Runde=gib_Runde(),Menge=kraftwerke.objects.get(id=1).maxLeistung/4)
                gebotequery.Preis=request.POST['kw1'+str(bid)]
                gebotequery.save()   
        else:
            formcoal=bidscoal() 
             
        if formgas.is_valid():
            for bid in range(1,5):
                gebotequery, created =gebote.objects.get_or_create(idSpieler=fb.gib_Spieler(request),idKW=2,idGebot=bid,Runde=gib_Runde(),Menge=kraftwerke.objects.get(id=2).maxLeistung/4)
                gebotequery.Preis=request.POST['kw2'+str(bid)]
                gebotequery.save()   
        else:
            formgas=bidsgas()
        if formwater.is_valid():
            for bid in range(1,5):
                gebotequery, created=gebote.objects.get_or_create(idSpieler=fb.gib_Spieler(request),idKW=3,idGebot=bid,Runde=gib_Runde(),Menge=kraftwerke.objects.get(id=3).maxLeistung/4)
                gebotequery.Preis=request.POST['kw3'+str(bid)]
                gebotequery.save()   
        else:
            formwater=bidswater()            
                              
    return render(request, 'boersenspiel/handler.html',{'html':fh.init_KraftwerksDiv(request),'formcoal':formcoal,'formwater':formwater, 'formgas':formgas, 'runde':fboersenspiel.gib_Runde()})

def login(request):
    return render(request, 'boersenspiel/login.html',{'runde':fboersenspiel.gib_Runde()})

def logout(request):
    auth_logout(request)
    return redirect('login')

def admin(request):
    if request.user.is_staff:
        if(request.GET.get('resetGame')):
            fadmin.reset(request,0)
        if(request.GET.get('resetAll')):
            fadmin.reset(request,1)
        if(request.GET.get('lade')):
            fadmin.ladedaten()
        if(request.GET.get('neueRunde')):
            fadmin.neueRunde()
        if(request.GET.get('auktion')):
            fadmin.auktion()           
        return render(request, 'boersenspiel/admin.html',{'runde':fboersenspiel.gib_Runde()})
    else:
        return redirect('login')
    raise Http404

def prefs(request):
    form=einstellungenForm(request.POST)
    if form.is_valid():
            einstellungquery=einstellungen.objects.get()
            einstellungquery.Runde=request.POST['Runde']
            einstellungquery.idSpiel=request.POST['Spiel']
            einstellungquery.auctiontype=request.POST['auctiontype']
            einstellungquery.nextround=request.POST['nextround']
            einstellungquery.rundenzeit=request.POST['rundenzeit']
            einstellungquery.save()
    else:
        form=einstellungenForm()
    return render(request,'boersenspiel/prefs.html',{'form':form, 'runde':fboersenspiel.gib_Runde()})

def externalmarkets(request):
    return render(request,'boersenspiel/markets.html',{'runde':fboersenspiel.gib_Runde()})

def highscores(request):
    data=[]
    spielerListe=Spieler.objects.all()
    for spieler in spielerListe:
        name=spieler.user.username
        gewinn=0.0
        for x in range(1,4):
            gewinn+=spielerkraftwerke.objects.get(idSpieler=spieler.pk,idKraftwerk=x).gewinn
        data=data+[(name,gewinn)]
    data.sort(key=lambda tup:tup[1],reverse=True)
    return render(request,'boersenspiel/hs.html',{'liste':data, 'runde':fboersenspiel.gib_Runde()})

def auctionsresults(request):
    dataGesamt=[]
    dataSpieler=[]
    
    for i in range(1,gib_Runde()+1):
        dataGesamt.append('boersenspiel/images/tmp/GesamtMeritOrder'+str(i)+'.png') 
    dataGesamt.reverse()    
    for j in range(1,gib_Runde()+1):
        dataSpieler.append('boersenspiel/images/tmp/PhenMeritOrder'+str(j)+'.png')
    dataSpieler.reverse()
    
        
    return render(request,'boersenspiel/results.html',{'runde':fboersenspiel.gib_Runde(),'gesamt':dataGesamt,'spieler':dataSpieler})

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/admin.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}

<div class="ueberschrift">Adminbereich</div>
<br />
<table>
        <td>
        <form action="{% url 'admin' %}" method="get">
            <input type="submit" value="Auktion" name="auktion"/>
        </form>
    </td>
    <td>
        Führt die Auktion zur aktuellen Runde durch und erstellt ensprechende Grafiken
    </td>
    <tr>
    <td>
        <form action="{% url 'admin' %}" method="get">
            <input type="submit" value="nächste Runde" name="neueRunde"/>
        </form>
    </td>
    <td>
        Beginnt die nächste Runde! FÜHRT KEINE AUKTION DURCH -> Vorher machen!
    </td>
    <tr>
    <td>
        <form action="{% url 'admin' %}" method="get">
            <input type="submit" value="Reset All" name="resetAll"/>
        </form>
    </td>
    <td>
        Löscht alle Spieler, Spielstände und Grafiken, setzt Runde auf 1. 
    </td>
    <tr>
    <td>
       <form action="{% url 'admin' %}" method="get">
            <input type="submit" value="Reset Game" name="resetGame"/>
        </form>
    </td>
    <td>
        Löscht alle Spielstände und Grafiken, setzt Runde auf 1. Behält Spieler bei!
    </td>
    <tr>
    <td>
        <form action="{% url 'admin' %}" method="get">
            <input type="submit" value="Lade Standard Daten" name="lade"/>
        </form>
    </td>
    <td>
        Lädt die Standard Daten wieder ein (Brennstoffpreise, Lastgang etc...)
    </td>
    <tr>
</tr>
</table>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>JERI Strombörsenspiel</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'boersenspiel/css/bootstrap.min.css' %}" rel="stylesheet" >
        <!-- Custom styles for this template -->
        <link href="{% static 'boersenspiel/css/starter-template.css' %}" rel="stylesheet" >
    </head>
    <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'boersenspiel:handler' %}">Trading Floor</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'boersenspiel:results' %}">Auction Results <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boersenspiel:markets' %}">External Markets</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boersenspiel:hs' %}">Highscores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Chat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
{% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boersenspiel:prefs' %}">Prefs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boersenspiel:admin' %}">Admin</a>
          </li>
{% endif %}
{% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'boersenspiel:logout' %}">Logout</a>
          </li> 
{% endif %}                   
        </ul>
      </div>
      <div>
      <p style="color:#FFFFFF" >Name:{{ request.user.username }}<br/>Runde:{{runde}}<br/>Game:{{ request.user.spieler.idSpiel }}#TODO
      </div>
    </nav>

    <div class="container">
        <div class="starter-template">
            {% block content %}
            {% endblock %}
        </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'boersenspiel/bootstrap/assets/js/vendor/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'boersenspiel/bootstrap/assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'boersenspiel/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'boersenspiel/bootstrap/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/handler.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}
{% autoescape off %}

    <div id="kraftwerkefeld">
        <div class="ueberschrift">My Powerplants</div>
        <br />
            <table>
                <td class=noframe><img src="{% static 'boersenspiel/images/coal.png' %}"></td><td class="noframe spacer"></td>
                <td class=noframe><img src="{% static 'boersenspiel/images/gas.png' %}"></td><td class="noframe spacer"></td>
                <td class=noframe><img src="{% static 'boersenspiel/images/wasser.png' %}"></td>
                <tr>{{html}}</tr>
                <tr><form action="{% url 'handler' %}" method="post">
                    <td><table>Angebot pro Block Kohle in EUR/MWh<br/>{{ formcoal.as_table}}</table></td><td class="noframe spacer"></td>
                    <td><table>Angebot pro Block Gas in EUR/MWh<br/>{{ formgas.as_table}}</table></td><td class="noframe spacer"></td>
                    <td><table>Angebot pro Block Wasser in EUR/MWh<br/>{{ formwater.as_table}}</table></td>
                    
                </form> 
                </tr>
            </table>
            <input type="submit" value="Submit" />  
    </div>
{% endautoescape %}
{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/hs.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}
        <div class="ueberschrift">Highscores</div>
        <br />
<table width="300">
<tr><th>#. Name:</th><th>Gewinn:</th><tr>
{% for name,gewinn in liste %}
   <tr><td>{{ name|linenumbers }}</td><td>{{gewinn}} Euro</td></tr>
{%endfor %}
</table>

{% endblock %}


JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/login.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}

{% block title %}Login{% endblock %}
{%block content%}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'handler' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/markets.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}
        <div class="ueberschrift">Preise</div>
        <br />
<div>
    <img src="{% static 'boersenspiel/images/tmp/kohlepreise.png' %}" alt="Not Found kohlepreise", height="300",width="300">
    <img src="{% static 'boersenspiel/images/tmp/gaspreise.png' %}" alt="Not Found kohlepreise", height="300",width="300">
</div>
<div>
    <img src="{% static 'boersenspiel/images/tmp/Wasserpreise.png' %}" alt="Not Found kohlepreise", height="300",width="300">
    <img src="{% static 'boersenspiel/images/tmp/Co2preise.png' %}" alt="Not Found kohlepreise", height="300",width="300">
</div>

{% endblock %}


JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/prefs.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}
        <div class="ueberschrift">Einstellungen</div>
        <br />
<form action="{% url 'prefs' %}" method="post">
    <table>{{form.as_table}}</table>
    <input type="submit" value="Submit" />  
</form> 
{% endblock %}

JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/results.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}
{% load static %}
{% block content %}
<div class="ueberschrift">Preis Verlauf Gesamt
    <table>
    <td><img src="{% static 'boersenspiel/images/tmp/Boersenpreise.png' %}" alt="Not Found Boersenpreise" height="300" width="400"></td>
    </table>
</div>
</br>
<div class="ueberschrift">Merit Order Verlauf Gesamt
    <table>
    {% for item in gesamt%}
    <td><img src="{% static item %}" alt="Picture not found" height="300" width="400"></td>
    {%endfor%}
    </table>
</div>
</br>
<div class="ueberschrift">MeritOrder Verlauf {{request.user.username}}
    <table>
    {% for item in spieler%}
    <td><img src="{% static item %}" alt="Picture not found" height="300" width="400"></td>
    {%endfor%}
    </table>
</div>
</br>


{% endblock %}


JERI_virtuelles_Energiesystemlabor/jeriapps/boersenspiel/templates/boersenspiel/signup.html
<!DOCTYPE html>
{% extends 'boersenspiel/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% for field in form %}
	{% csrf_token %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}